<?php

/**
 * @file
 * Provides cancel by functionality for the Entity Registration module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function registration_cancel_by_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'registration_settings') {
    $fields['cancel_by'] = BaseFieldDefinition::create('datetime')
      ->setLabel(t('Cancel by date'))
      ->setDescription(t('When registrations must be canceled by.'))
      ->setRequired(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'datetime_default',
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }
  return $fields;
}

/**
 * Implements hook_entity_type_alter().
 */
function registration_cancel_by_entity_type_alter(array &$entity_types) {
  // Validate the "cancel by" date in registration settings.
  $entity_types['registration_settings']->addConstraint('CancelByConstraint');
}
