# See https://ddev.readthedocs.io/en/stable/users/configuration/config
name: private-message
type: drupal
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - DRUPAL_CORE=^11
corepack_enable: true
