# Documentation https://project.pages.drupalcode.org/gitlab_templates/

include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _SHOW_ENVIRONMENT_VARIABLES: 1
  DRUPAL_CORE: "$CORE_STABLE"
  _TARGET_PHP: "$CORE_PHP_MIN"
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_MAX_PHP: 1
  SKIP_NIGHTWATCH: 1

cspell:
  allow_failure: false
eslint:
  allow_failure: false
stylelint:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: false
