# Schema for the configuration files of the Request API Key Authentication module.
services_api_key_auth.api_key.*:
  type: config_entity
  label: 'API Key configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    uuid:
      type: string
    key:
      type: string
      Label: 'API Key'
    user_uuid:
      type: string

services_api_key_auth.settings:
  type: config_object
  label: 'Request API Key Authentication settings'
  mapping:
    api_key_request_header_name:
      type: string
      label: 'API Key Request header name'
    api_key_post_parameter_name:
      type: string
      label: 'API Key POST parameter name'
    api_key_get_parameter_name:
      type: string
      label: 'API Key GET parameter name'
