# Schema for the Registration Inline Entity Form module.

field.widget.settings.inline_entity_form_settings:
  type: mapping
  label: 'Registration inline entity form widget settings'
  mapping:
    hide_register_tab:
      type: boolean
      label: 'Hide Register Tab'
    form_mode:
      type: string
      label: "Form mode"
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: label
      label: "Label (singular)"
    label_plural:
      type: label
      label: "Label (plural)"
    collapsible:
      type: boolean
      label: "Collapsible"
    collapsed:
      type: boolean
      label: "Collapsed by default"
    revision:
      type: boolean
      label: "Create new revision"
