features:
  node_user_picture: 0
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
logo_path_anonymous: 'public://logo_principal_0.jpg'
favicon:
  use_default: 1
aristotle_use_header_background: 0
aristotle_header_image_path: ''
aristotle_header_image_upload: {  }
aristotle_home_page_settings:
  aristotle_use_home_page_markup: 0
  aristotle_home_page_slides:
    1:
      aristotle_home_page_image_path: ''
      aristotle_home_page_image_upload: {  }
    actions: {  }
aristotle_menu_source: '0'
aristotle_menu_show_for_anonymous: 1
