<?php

/**
 * @file
 * Implements the Augmentor module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function augmentor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.augmentor':
      $output = '';
      $output .= '<h3>' . t('Augmentor') . '</h3>';
      $output .= '<p>' . t('Integration module which allows content to be augmented in Drupal via connections with external services.') . '</p>';
      return $output;
  }
}
