<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for Testmodule module.
 */

/**
 * Implements hook_theme().
 */
function testmodule_theme(): array {
  return [
    'moodle_courses' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for moodle-courses.html.twig template.
 *
 * Default template: moodle-courses.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_moodle_courses(array &$variables): void {
  $variables['foo'] = 'bar';
}
